[build] 
  publish = "dist" 
  command = "npm run build" 
 
[build.environment] 
  NODE_VERSION = "18" 
  NPM_FLAGS = "--production=false" 
 
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw-notifications.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache"

[[redirects]] 
  from = "/*" 
  to = "/index.html" 
  status = 200 
